### ISSUE TITLE
uni-code issue rendering on ipadOS

### ISSUE THREAD

**Issue by cuter-doc0** [AlexFlorides/javascript-calculator#14]
came across an issue where if server is not explicit about unicode the render will fail on an ipad - adding the below to the index.html head resolved the issue:

`<meta http-equiv="Content-Type" content="text/html; charset=utf-8">`

Screenshot of error:
 ![IMG_E3970036501A-1](https://github.com/AlexFlorides/javascript-calculator/assets/124633877/0670a0cc-b606-48fe-a0a6-f8a3f9ef9d7e)

**Comment by AlexFlorides** [comment]
Nice observation. Wanna fix it and create a new pull request to merge it?
