### ISSUE TITLE
History Display

### ISSUE THREAD

**Issue by allen-clarke** [AlexFlorides/javascript-calculator#18]
The history of the operation displays outside the dashboard. For example, when I type 8 + 8,  it displays outside the dashboard. Only the answer displays inside the dashboard

**Comment by AlexFlorides** [comment]
![history](https://github.com/AlexFlorides/javascript-calculator/assets/47948084/7ea097e0-4513-4eeb-b8c5-7c0222193ee8)

If this is what you are talking about, this is how it's supposed to be. The latest operation should be displayed above the result, not inside the box along with the result.
