### ISSUE TITLE
Paste number into the display field

### ISSUE THREAD

**Issue by eandmsz** [AlexFlorides/javascript-calculator#4]
You can already copy the result number from the output field.
It would be great if you could paste in as well (not appending to the existing number but overwriting it).

With this you can skip the implementation of the memory functions, since the clipboard can be used in almost all cases instead.

**Comment by SavainB** [comment]
can i work on this issues ?

**Comment by AlexFlorides** [comment]
Of course

**Comment by RuneBlast** [comment]
Hello, I forgot to send a message here. I'm working with SavainB, can i be assigned to this issue too please ?

**Comment by AlexFlorides** [comment]
Okay good
